export const recipeElements = {
    'pink': ['Pink Plort', 'plorts/pink', ['slimes', '', 'pink']],
    'cotton': ['Cotton Plort', 'plorts/cotton', ['slimes', '', 'cotton']],
    'tabby': ['Tabby Plort', 'plorts/tabby', ['slimes', '', 'tabby']],
    'rock': ['Rock Plort', 'plorts/rock', ['slimes', '', 'rock']],
    'phosphor': ['Phosphor Plort', 'plorts/phosphor', ['slimes', '', 'phosphor']],
    'boom': ['Boom Plort', 'plorts/boom', ['slimes', '', 'boom']],
    'hunter': ['Hunter Plort', 'plorts/hunter', ['slimes', '', 'hunter']],
    'crystal': ['Crystal Plort', 'plorts/crystal', ['slimes', '', 'crystal']],
    'fire': ['Fire Plort', 'plorts/fire', ['slimes', '', 'fire']],
    'batty': ['Batty Plort', 'plorts/batty', ['slimes', '', 'batty']],
    'flutter': ['Flutter Plort', 'plorts/flutter', ['slimes', '', 'flutter']],
    'gold': ['Gold Plort', 'plorts/gold', ['slimes', '', 'gold']],
    'saber': ['Saber Plort', 'plorts/saber', ['slimes', '', 'saber']],
    'angler': ['Angler Plort', 'plorts/angler', ['slimes', '', 'angler']],
    'ringtail': ['Ringtail Plort', 'plorts/ringtail', ['slimes', '', 'ringtail']],
    'radiant': ['Radiant Ore', 'resources/radiant', ['resources', '', 'radiant']],
    'honey': ['Honey Plort', 'plorts/honey', ['slimes', '', 'honey']],
    'wax': ['Buzz Wax', 'resources/wax', ['items', 'resources', 'wax']],
    'wildHoney': ['Wild Honey', 'resources/honey', ['resources', '', 'honey']],
    'brine': ['Deep Brine', 'resources/brine', ['resources', '', 'brine']],
    'jelly': ['Jellystone', 'resources/jelly', ['resources', '', 'jelly']],
    'snowflake': ['Perfect Snowflake', 'resources/snowflake', ['resources', '', 'snowflake']],
    'sunsap': ['Sun Sap', 'resources/sunsap', ['resources', '', 'sunsap']],
    'drift': ['Drift Crystal', 'resources/drift', ['resources', '', 'drift']],
    'glass': ['Storm Glass', 'resources/glass', ['resources', '', 'glass']],
    'mote': ['Lightning Mote', 'resources/mote', ['resources', '', 'mote']],
    'lava': ['Lava Dust', 'resources/lava', ['resources', '', 'lava']],
    'primordy': ['Primordy Oil', 'resources/primordy', ['resources', '', 'primordy']],
    'fossil': ['Slime Fossil', 'resources/fossil', ['resources', '', 'fossil']],
    'sand': ['Silky Sand', 'resources/sand', ['resources', '', 'sand']],
    'diamond': ['Strange Diamond', 'resources/diamond', ['resources', '', 'diamond']],
    'tankLiner': ['Tank Liner', 'upgrades/tankLiner', ['upgrades', '', 'tankLiner']],
    'storageCell': ['Storage Cell', 'upgrades/storageCell', []],
    'storageUnit': ['Storage Unit', 'upgrades/storageUnit', []],
    'powerChip': ['Power Chip', 'upgrades/powerChip', []],
    'dashBootModule': ['Dash Boot Module', 'upgrades/dashBootModule', []],
    'jetpackDrive': ['Jetpack Drive', 'upgrades/jetpackDrive', []],
    'heartModule': ['Heart Module', 'upgrades/heartModule', []],
    'sureshotModule': ['Sureshot Module', 'upgrades/sureshotModule', []],
    'droneKey': ['Drone Key', 'upgrades/droneKey', []],
    'sureshotModule:': ['Sureshot Module', 'upgrades/sureshotModule', []]
}

export const unlockRequirements = {
    'start': ['Available at the start', 'misc/check'],
    'pod': ['Unlocked via a Pod', 'misc/pod'],
    'polestar': ['Unlocked via Polestar Provisions', 'misc/polestar'],
    'mochi': ['Given by Mochi Miles', 'ranchers/mochi'],
    'viktor': ['Given by Viktor Humphries', 'ranchers/viktor'],
    'ogden': ['Given by Ogden Ortiz', 'ranchers/ogden'],
    'bob': ['Given by Bob', 'ranchers/bob'],
    'thora': ['Given by Thora West', 'ranchers/thora'],
}

export const upgradeNames = [
    'harvester',
    'health',
    'power',
    'dash',
    'jetpack',
    'tankBooster',
    'extraTank',
    'waterTank',
    'pulseWave',
    'tankGuard',
    'droneKey',
    'sureshot'
]

export const upgradePacks = {
    'harvester': ['Resource Harvester', 1],
    'health': ['Health Modules', 3],
    'power': ['Power Modules', 4],
    'dash': ['Dash Boots Speed', 2],
    'jetpack': ['Jetpack', 2],
    'tankBooster': ['Tank Capacity', 4],
    'extraTank': ['Extra Tanks', 2],
    'waterTank': ['Dedicated Water Tank', 1],
    'pulseWave': ['Pulse Wave', 1],
    'tankGuard': ['Tank Loss Prevention', 3],
    'droneKey': ['Drone Archive Key', 1],
    'sureshot': ['Golden Sureshot Modules', 3]
}

export const upgradesList = {
    'harvester1': ['Resource Harvester', 'start', 450, { 'cotton': 10 }],
    'health1': ['Heart Module I', 'start', 450, { 'pink': 10 }],
    'health2': ['Heart Module II', 'pod', 900, { 'pink': 20, 'honey': 10, 'brine': 10, 'jelly': 10, 'heartModule': 1 }],
    'health3': ['Heart Module III', 'pod', 3000, { 'pink': 30, 'honey': 20, 'brine': 30, 'sand': 10, 'heartModule': 1 }],
    'power1': ['Power Module I', 'start', 450, { 'cotton': 10 }],
    'power2': ['Power Module II', 'pod', 900, { 'cotton': 20, 'batty': 10, 'primordy': 10, 'jelly': 10, 'powerChip': 1 }],
    'power3': ['Power Module III', 'pod', 3000, { 'cotton': 30, 'batty': 20, 'wildHoney': 10, 'primordy': 30, 'powerChip': 1 }],
    'power4': ['Power Module IV', 'pod', 10000, { 'cotton': 50, 'saber': 30, 'fossil': 30, 'sunsap': 1, 'powerChip': 1 }],
    'dash1': ['Dash Module I', 'start', 450, { 'boom': 10 }],
    'dash2': ['Dash Module II', 'pod', 1500, { 'boom': 20, 'flutter': 10, 'wildHoney': 10, 'lava': 10, 'dashBootModule': 1 }],
    'jetpack1': ['Jetpack I', 'start', 450, { 'phosphor': 10, 'radiant': 10 }],
    'jetpack2': ['Jetpack II', 'pod', 1500, { 'phosphor': 20, 'batty': 10, 'radiant': 20, 'wildHoney': 10, 'jetpackDrive': 1 }],
    'tankBooster1': ['Tank Booster I', 'start', 450, { 'tabby': 10 }],
    'tankBooster2': ['Tank Booster II', 'pod', 900, { 'tabby': 20, 'angler': 10, 'radiant': 10, 'jelly': 10, 'storageCell': 1 }],
    'tankBooster3': ['Tank Booster III', 'pod', 3000, { 'tabby': 30, 'angler': 20, 'radiant': 30, 'lava': 10, 'storageCell': 1 }],
    'tankBooster4': ['Tank Booster IV', 'pod', 10000, { 'tabby': 40, 'saber': 30, 'snowflake': 30, 'sunsap': 1, 'storageCell': 1 }],
    'extraTank1': ['Extra Tank I', 'start', 1500, { 'rock': 10, 'sand': 10 }],
    'extraTank2': ['Extra Tank II', 'pod', 3000, { 'rock': 40, 'ringtail': 20, 'sand': 20, 'diamond': 2, 'storageUnit': 1 }],
    'waterTank1': ['Water Tank', 'start', 450, { 'brine': 10 }],
    'pulseWave1': ['Pulse Wave', 'start', 450, { 'flutter': 10, 'jelly': 10, 'wildHoney': 5 }],
    'tankGuard1': ['Tank Guard I', 'pod', 3000, { 'crystal': 20, 'hunter': 10, 'wax': 10, 'lava': 10, 'tankLiner': 1 }],
    'tankGuard2': ['Tank Guard II', 'pod', 6000, { 'crystal': 30, 'hunter': 20, 'wax': 10, 'diamond': 1, 'tankLiner': 1 }],
    'tankGuard3': ['Tank Guard III', 'pod', 12000, { 'crystal': 40, 'hunter': 30, 'wax': 20, 'diamond': 2, 'tankLiner': 1 }],
    'droneKey1': ['Drone Archive Key', 'mochi', 450, { 'hunter': 20, 'fire': 20, 'jelly': 20, 'lava': 10, 'droneKey': 1 }],
    'sureshot1': ['Golden Sureshot I', 'pod', 1500, { 'fire': 20, 'gold': 1, 'snowflake': 10, 'sunsap': 1, 'sureshotModule:': 1 }],
    'sureshot2': ['Golden Sureshot II', 'pod', 3000, { 'saber': 30, 'gold': 2, 'snowflake': 20, 'sunsap': 2, 'sureshotModule:': 1 }],
    'sureshot3': ['Golden Sureshot III', 'pod', 6000, { 'saber': 40, 'gold': 3, 'snowflake': 30, 'sunsap': 3, 'sureshotModule:': 1 }],
}

export const upgradeDescriptions = {
    'harvester1': "Adds a resonator to the vac's suction mechanism that shakes loose science resources from nodes in the environment.",
    'health1': "Syncs with your body's own vital processes to enhance life systems, boosting health to 150. Plus, it's sparkly.",
    'health2': "A more advanced and even sparklier heart module that boosts health to 200.",
    'health3': "The ultimate in heart module technology, boosting health to 250.",
    'power1': "Augments your vackpack with an almost-certainly-safe micro fusion generator that boosts energy to 150.",
    'power2': "This enhanced micro generator boosts energy to 200; but more importantly, is even smaller.",
    'power3': "The latest micro generator boosts energy to 250; but not high enough to give up coffee entirely.",
    'power4': "An impossibly advanced micro generator boosts personal energy to 275. There's no way this is still legal.",
    'dash1': "These highly advanced and, frankly, fashion-forward boots reduce the energy consumption of sprinting.",
    'dash2': "Experimental footwear capable of reducing the cost of sprinting even further. It makes you think walking is for suckers.",
    'jetpack1': "Keep your head in the clouds with this amazing, personal jetpack!",
    'jetpack2': "Enhanced jetpack thrusters that consume 20% less energy but produce double the fun.",
    'tankBooster1': "Improved nano-storage cell technology allows your vac tanks to hold 30 units of whatever you can vac up.",
    'tankBooster2': "These enhanced nano-storage cells throw caution to the wind and allow you to cram 40 units into each vac tank.",
    'tankBooster3': "More is better, but in this case, it's best. These premium nano-storage cells can hold 50 units in each vac tank.",
    'tankBooster4': "The secret best vac tank available using experimental nano-storage technology that's absolutely probably maybe legal.",
    'extraTank1': "Adds an extra general-purpose vac tank.",
    'extraTank2': "Adds yet another extra general-purpose vac tank.",
    'waterTank1': "Adds a specialized vac tank that allows you to store fresh water.",
    'pulseWave1': "Adds a pulse wave emitter feature to your vacpack that pushes away slimes whenever you need some personal space.",
    'tankGuard1': "Salvages 20% of your vac tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'tankGuard2': "Salvages 40% of your vac tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'tankGuard3': "Salvages 60% of your vac's tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'droneKey1': "Utilizes Miles tech decryption algorithms to unlock access to archived logs on Research Drones.",
    'sureshot1': "A special vacpack upgrade that hones in on gold slime weakpoints (their secret bellybutton?) and doubles the amount of gold plorts they produce when hit.",
    'sureshot2': "Upgrades the Sureshot's focusing lens, reducing the glare from those shiny, bright gold slimes. This triples the amount of plorts they produce when hit.",
    'sureshot3': "The ultimate in Sureshot technology, this upgrade quadruples the amount of gold plorts produced when hitting gold slimes."
}

export const upgradeEffects = {
    'harvester1': [['misc/none', ''], ['upgrades/harvester', '+ Resource Harvester']],
    'health1': [['misc/health', '100 Health'], ['misc/health', '150 Health (+50)']],
    'health2': [['misc/health', '150 Health'], ['misc/health', '200 Health (+50)']],
    'health3': [['misc/health', '200 Health'], ['misc/health', '250 Health (+50)']],
    'power1': [['misc/energy', '100 Energy'], ['misc/energy', '150 Energy (+50)']],
    'power2': [['misc/energy', '150 Energy'], ['misc/energy', '200 Energy (+50)']],
    'power3': [['misc/energy', '200 Energy'], ['misc/energy', '250 Energy (+50)']],
    'power4': [['misc/energy', '250 Energy'], ['misc/energy', '275 Energy (+25)']],
    'dash1': [['misc/none', ''], ['upgrades/dash', '- Sprint Energy Consumption']],
    'dash2': [['misc/none', ''], ['upgrades/dash', '- Sprint Energy Consumption']],
    'jetpack1': [['misc/none', ''], ['upgrades/jetpack', 'Jetpack']],
    'jetpack2': [['misc/none', 'Jetpack'], ['upgrades/jetpack', '- Jetpack Energy Consumption']],
    'tankBooster1': [['upgrades/tankBooster', '20 Units Capacity'], ['upgrades/tankBooster', '30 Units Capacity (+10)']],
    'tankBooster2': [['upgrades/tankBooster', '30 Units Capacity'], ['upgrades/tankBooster', '40 Units Capacity (+10)']],
    'tankBooster3': [['upgrades/tankBooster', '40 Units Capacity'], ['upgrades/tankBooster', '50 Units Capacity (+10)']],
    'tankBooster4': [['upgrades/tankBooster', '50 Units Capacity'], ['upgrades/tankBooster', '60 Units Capacity (+10)']],
    'extraTank1': [['upgrades/extraTank', '4 Tanks'], ['upgrades/extraTank', '5 Tanks (+1)']],
    'extraTank2': [['upgrades/extraTank', '5 Tanks'], ['upgrades/extraTank', '6 Tanks (+1)']],
    'waterTank1': [['misc/none', ''], ['upgrades/waterTank', '+ Water Tank']],
    'pulseWave1': [['misc/none', ''], ['upgrades/pulseWave', '+ Pulse Wave']],
    'tankGuard1': [['misc/death', 'Full Loss on Death'], ['upgrades/tankGuard', '30% Salvage on Death']],
    'tankGuard2': [['upgrades/tankGuard', '30% Salvage on Death'], ['upgrades/tankGuard', '40% Salvage on Death']],
    'tankGuard3': [['upgrades/tankGuard', '40% Salvage on Death'], ['upgrades/tankGuard', '60% Salvage on Death']],
    'droneKey1': [['misc/none', ''], ['upgrades/droneKey', '+ Drone Archive Key']],
    'sureshot1': [['slimes/gold', '1 Plorts per Gold Slime Fed'], ['slimes/gold', '2 Plorts per Gold Slime Fed']],
    'sureshot2': [['slimes/gold', '2 Plorts per Gold Slime Fed'], ['slimes/gold', '3 Plorts per Gold Slime Fed']],
    'sureshot3': [['slimes/gold', '3 Plorts per Gold Slime Fed'], ['slimes/gold', '4 Plorts per Gold Slime Fed']]
}

export const warpGadgets = {
    'teleporthomegreen': ['Green Home Portal', 'viktor', 800, { 'angler': 20, 'radiant': 10, 'wax': 10, 'wildHoney': 5 }, null],
    'teleporthomeblue': ['Blue Home Portal', 'viktor', 250, { 'rock': 10, 'radiant': 10, 'primordy': 5 }, null],
    'teleporthomered': ['Red Home Portal', 'viktor', 800, { 'boom': 20, 'jelly': 10, 'primordy': 10, 'lava': 5 }, null],
    'teleporthomeyellow': ['Yellow Home Portal', 'viktor', 250, { 'cotton': 10, 'jelly': 10, 'brine': 10 }, null],
    'teleportev': ['Ember Valley Portal', 'pod', 1000, { 'fire': 20, 'crystal': 10, 'radiant': 10, 'primordy': 10, 'diamond': 1 }, null],
    'teleportss': ['Starlight Strand Portal', 'pod', 1000, { 'hunter': 20, 'honey': 10, 'radiant': 10, 'wax': 10, 'diamond': 1 }, null],
    'teleportpb': ['Powderfall Bluffs Portal', 'pod', 1000, { 'saber': 20, 'puddle': 5, 'radiant': 10, 'fossil': 10, 'diamond': 1 }, null],
    'teleportblue': ['Blue Teleporter', 'viktor', 1200, { 'rock': 30, 'brine': 20, 'radiant': 20, 'honey': 10, 'diamond': 2 }, 'teleportblue'],
    'teleportgrey': ['Grey Teleporter', 'viktor', 1200, { 'tabby': 30, 'wax': 20, 'radiant': 20, 'sand': 10, 'diamond': 2 }, 'teleportgrey'],
    'teleportpink': ['Pink Teleporter', 'viktor', 1200, { 'pink': 30, 'jelly': 20, 'radiant': 20, 'lava': 10, 'diamond': 2 }, 'teleportpink'],
    'teleportviolet': ['Violet Teleporter', 'viktor', 1200, { 'phosphor': 30, 'primordy': 20, 'radiant': 20, 'sand': 10, 'diamond': 2 }, 'teleportviolet'],
    'teleportwhite': ['Snowy Teleporter', 'viktor', 1200, { 'saber': 30, 'fossil': 20, 'radiant': 20, 'lava': 10, 'diamond': 2 }, 'teleportwhite'],
    'warpdepotblue': ['Blue Warp Depot', 'pod', 250, { 'rock': 20, 'wax': 10, 'radiant': 3, 'sand': 3 }, 'warpdepotblue'],
    'warpdepotgrey': ['Grey Warp Depot', 'pod', 250, { 'tabby': 20, 'brine': 10, 'radiant': 5, 'lava': 3 }, 'warpdepotgrey'],
    'warpdepotpink': ['Pink Warp Depot', 'pod', 250, { 'pink': 20, 'primordy': 10, 'radiant': 5, 'sand': 3 }, 'warpdepotpink'],
    'warpdepotviolet': ['Violet Warp Depot', 'pod', 250, { 'batty': 20, 'jelly': 10, 'radiant': 5, 'wildHoney': 3 }, 'warpdepotviolet'],
    'warpdepotwhite': ['Snowy Warp Depot', 'pod', 250, { 'saber': 20, 'snowflake': 10, 'radiant': 5, 'wildHoney': 3 }, 'warpdepotwhite'],
    'marketlink': ['Market Link', 'mochi', 250, { 'pink': 20, 'wax': 10, 'primordy': 10, 'sand': 5 }, null],
    'refinerylink': ['Refinery Link', 'mochi', 250, { 'phosphor': 10, 'jelly': 10, 'brine': 5 }, null],
    'linkedcannonblue': ['Blue Linked Cannon', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, 'linkedcannonblueout'],
    'linkedcannongrey': ['Grey Linked Cannon', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, 'linkedcannongreyout'],
    'linkedcannonpink': ['Pink Linked Cannon', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, 'linkedcannonpinkout'],
    'linkedcannonblueout': ['Blue Linked Cannon Output', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, undefined],
    'linkedcannongreyout': ['Grey Linked Cannon Output', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, undefined],
    'linkedcannonpinkout': ['Pink Linked Cannon Output', 'polestar', 1000, { 'batty': 10, 'mote': 3 }, undefined],
}

export const warpNames = [
    "teleporthomegreen",
    "teleporthomeblue",
    "teleporthomered",
    "teleporthomeyellow",
    "teleportev",
    "teleportss",
    "teleportpb",
    "teleportblue",
    "teleportgrey",
    "teleportpink",
    "teleportviolet",
    "teleportwhite",
    "warpdepotblue",
    "warpdepotgrey",
    "warpdepotpink",
    "warpdepotviolet",
    "warpdepotwhite",
    "marketlink",
    "refinerylink",
    "linkedcannonblue",
    "linkedcannongrey",
    "linkedcannonpink"
];