export const recipeElements = {
    'newbucks': ['Newbucks', 'misc/buck', ''],
    'pink': ['Pink Plort', 'plorts/pink', 'slimes/pink'],
    'cotton': ['Cotton Plort', 'plorts/cotton', 'slimes/cotton'],
    'tabby': ['Tabby Plort', 'plorts/tabby', 'slimes/tabby'],
    'rock': ['Rock Plort', 'plorts/rock', 'slimes/rock'],
    'phosphor': ['Phosphor Plort', 'plorts/phosphor', 'slimes/phosphor'],
    'puddle': ['Puddle Plort', 'plorts/puddle', 'slimes/puddle'],
    'boom': ['Boom Plort', 'plorts/boom', 'slimes/boom'],
    'hunter': ['Hunter Plort', 'plorts/hunter', 'slimes/hunter'],
    'crystal': ['Crystal Plort', 'plorts/crystal', 'slimes/crystal'],
    'fire': ['Fire Plort', 'plorts/fire', 'slimes/fire'],
    'batty': ['Batty Plort', 'plorts/batty', 'slimes/batty'],
    'flutter': ['Flutter Plort', 'plorts/flutter', 'slimes/flutter'],
    'gold': ['Gold Plort', 'plorts/gold', 'slimes/gold'],
    'saber': ['Saber Plort', 'plorts/saber', 'slimes/saber'],
    'angler': ['Angler Plort', 'plorts/angler', 'slimes/angler'],
    'ringtail': ['Ringtail Plort', 'plorts/ringtail', 'slimes/ringtail'],
    'radiant': ['Radiant Ore', 'resources/radiant', 'resources/radiant'],
    'honey': ['Honey Plort', 'plorts/honey', 'slimes/honey'],
    'wax': ['Buzz Wax', 'resources/wax', 'resources/wax'],
    'wildHoney': ['Wild Honey', 'resources/honey', 'resources/honey'],
    'brine': ['Deep Brine', 'resources/brine', 'resources/brine'],
    'jelly': ['Jellystone', 'resources/jelly', 'resources/jelly'],
    'snowflake': ['Perfect Snowflake', 'resources/snowflake', 'resources/snowflake'],
    'sunsap': ['Sun Sap', 'resources/sunsap', 'resources/sunsap'],
    'drift': ['Drift Crystal', 'resources/drift', 'resources/drift'],
    'glass': ['Storm Glass', 'resources/glass', 'resources/glass'],
    'mote': ['Lightning Mote', 'resources/mote', 'resources/mote'],
    'lava': ['Lava Dust', 'resources/lava', 'resources/lava'],
    'primordy': ['Primordy Oil', 'resources/primordy', 'resources/primordy'],
    'fossil': ['Slime Fossil', 'resources/fossil', 'resources/fossil'],
    'sand': ['Silky Sand', 'resources/sand', 'resources/sand'],
    'diamond': ['Strange Diamond', 'resources/diamond', 'resources/diamond'],
    'tankLiner': ['Tank Liner', 'upgrades/tankLiner', 'upgrades/tankLiner'],
    'storageCell': ['Storage Cell', 'upgrades/storageCell', ''],
    'storageUnit': ['Storage Unit', 'upgrades/storageUnit', ''],
    'powerChip': ['Power Chip', 'upgrades/powerChip', ''],
    'dashBootModule': ['Dash Boot Module', 'upgrades/dashBootModule', ''],
    'jetpackDrive': ['Jetpack Drive', 'upgrades/jetpackDrive', ''],
    'heartModule': ['Heart Module', 'upgrades/heartModule', ''],
    'sureshotModule': ['Sureshot Module', 'upgrades/sureshotModule', ''],
    'droneKey': ['Drone Key', 'upgrades/droneKey', ''],
    'sureshotModule:': ['Sureshot Module', 'upgrades/sureshotModule', '']
};

export const unlockRequirements = {
    'start': ['Available at the start', 'misc/check'],
    'pod': ['Unlocked via a Pod', 'misc/pod'],
    'polestar': ['Unlocked via Polestar Provisions', 'misc/polestar'],
    'mochi': ['Given by Mochi Miles', 'ranchers/mochi'],
    'viktor': ['Given by Viktor Humphries', 'ranchers/viktor'],
    'ogden': ['Given by Ogden Ortiz', 'ranchers/ogden'],
    'bob': ['Given by BOb', 'ranchers/bob'],
    'thora': ['Given by Thora West', 'ranchers/thora'],
};

export const upgradeNames = [
    'harvester',
    'health',
    'power',
    'dash',
    'jetpack',
    'tankBooster',
    'extraTank',
    'waterTank',
    'pulseWave',
    'tankGuard',
    'droneKey',
    'sureshot'
];

export const upgradePacks = {
    'harvester': ['Resource Harvester', 1],
    'health': ['Health Modules', 3],
    'power': ['Power Modules', 4],
    'dash': ['Dash Boots Speed', 2],
    'jetpack': ['Jetpack', 2],
    'tankBooster': ['Tank Capacity', 4],
    'extraTank': ['Extra Tanks', 2],
    'waterTank': ['Dedicated Water Tank', 1],
    'pulseWave': ['Pulse Wave', 1],
    'tankGuard': ['Tank Loss Prevention', 3],
    'droneKey': ['Drone Archive Key', 1],
    'sureshot': ['Golden Sureshot Modules', 3]
};

export const upgradesList = {
    'harvester1': ['Resource Harvester', 'start', { 'newbucks': 450, 'cotton': 10 }],
    'health1': ['Heart Module I', 'start', { 'newbucks': 450, 'pink': 10 }],
    'health2': ['Heart Module II', 'pod', { 'newbucks': 900, 'pink': 20, 'honey': 10, 'brine': 10, 'jelly': 10, 'heartModule': 1 }],
    'health3': ['Heart Module III', 'pod', { 'newbucks': 3000, 'pink': 30, 'honey': 20, 'brine': 30, 'sand': 10, 'heartModule': 1 }],
    'power1': ['Power Module I', 'start', { 'newbucks': 450, 'cotton': 10 }],
    'power2': ['Power Module II', 'pod', { 'newbucks': 900, 'cotton': 20, 'batty': 10, 'primordy': 10, 'jelly': 10, 'powerChip': 1 }],
    'power3': ['Power Module III', 'pod', { 'newbucks': 3000, 'cotton': 30, 'batty': 20, 'wildHoney': 10, 'primordy': 30, 'powerChip': 1 }],
    'power4': ['Power Module IV', 'pod', { 'newbucks': 10000, 'cotton': 50, 'saber': 30, 'fossil': 30, 'sunsap': 1, 'powerChip': 1 }],
    'dash1': ['Dash Module I', 'start', { 'newbucks': 450, 'boom': 10 }],
    'dash2': ['Dash Module II', 'pod', { 'newbucks': 1500, 'boom': 20, 'flutter': 10, 'wildHoney': 10, 'lava': 10, 'dashBootModule': 1 }],
    'jetpack1': ['Jetpack I', 'start', { 'newbucks': 450, 'phosphor': 10, 'radiant': 10 }],
    'jetpack2': ['Jetpack II', 'pod', { 'newbucks': 1500, 'phosphor': 20, 'batty': 10, 'radiant': 20, 'wildHoney': 10, 'jetpackDrive': 1 }],
    'tankBooster1': ['Tank Booster I', 'start', { 'newbucks': 450, 'tabby': 10 }],
    'tankBooster2': ['Tank Booster II', 'pod', { 'newbucks': 900, 'tabby': 20, 'angler': 10, 'radiant': 10, 'jelly': 10, 'storageCell': 1 }],
    'tankBooster3': ['Tank Booster III', 'pod', { 'newbucks': 3000, 'tabby': 30, 'angler': 20, 'radiant': 30, 'lava': 10, 'storageCell': 1 }],
    'tankBooster4': ['Tank Booster IV', 'pod', { 'newbucks': 10000, 'tabby': 40, 'saber': 30, 'snowflake': 30, 'sunsap': 1, 'storageCell': 1 }],
    'extraTank1': ['Extra Tank I', 'start', { 'newbucks': 1500, 'rock': 10, 'sand': 10 }],
    'extraTank2': ['Extra Tank II', 'pod', { 'newbucks': 3000, 'rock': 40, 'ringtail': 20, 'sand': 20, 'diamond': 2, 'storageUnit': 1 }],
    'waterTank1': ['Water Tank', 'start', { 'newbucks': 450, 'brine': 10 }],
    'pulseWave1': ['Pulse Wave', 'start', { 'newbucks': 450, 'flutter': 10, 'jelly': 10, 'wildHoney': 5 }],
    'tankGuard1': ['Tank Guard I', 'pod', { 'newbucks': 3000, 'crystal': 20, 'hunter': 10, 'wax': 10, 'lava': 10, 'tankLiner': 1 }],
    'tankGuard2': ['Tank Guard II', 'pod', { 'newbucks': 6000, 'crystal': 30, 'hunter': 20, 'wax': 10, 'diamond': 1, 'tankLiner': 1 }],
    'tankGuard3': ['Tank Guard III', 'pod', { 'newbucks': 12000, 'crystal': 40, 'hunter': 30, 'wax': 20, 'diamond': 2, 'tankLiner': 1 }],
    'droneKey1': ['Drone Archive Key', 'mochi', { 'newbucks': 450, 'hunter': 20, 'fire': 20, 'jelly': 20, 'lava': 10, 'droneKey': 1 }],
    'sureshot1': ['Golden Sureshot I', 'pod', { 'newbucks': 1500, 'fire': 20, 'gold': 1, 'snowflake': 10, 'sunsap': 1, 'sureshotModule:': 1 }],
    'sureshot2': ['Golden Sureshot II', 'pod', { 'newbucks': 3000, 'saber': 30, 'gold': 2, 'snowflake': 20, 'sunsap': 2, 'sureshotModule:': 1 }],
    'sureshot3': ['Golden Sureshot III', 'pod', { 'newbucks': 6000, 'saber': 40, 'gold': 3, 'snowflake': 30, 'sunsap': 3, 'sureshotModule:': 1 }],
};

export const upgradeDescriptions = {
    'harvester1': "Adds a resonator to the vac's suction mechanism that shakes loose science resources from nodes in the environment.",
    'health1': "Syncs with your body's own vital processes to enhance life systems, boosting health to 150. Plus, it's sparkly.",
    'health2': "A more advanced and even sparklier heart module that boosts health to 200.",
    'health3': "The ultimate in heart module technology, boosting health to 250.",
    'power1': "Augments your vackpack with an almost-certainly-safe micro fusion generator that boosts energy to 150.",
    'power2': "This enhanced micro generator boosts energy to 200; but more importantly, is even smaller.",
    'power3': "The latest micro generator boosts energy to 250; but not high enough to give up coffee entirely.",
    'power4': "An impossibly advanced micro generator boosts personal energy to 275. There's no way this is still legal.",
    'dash1': "These highly advanced and, frankly, fashion-forward boots reduce the energy consumption of sprinting.",
    'dash2': "Experimental footwear capable of reducing the cost of sprinting even further. It makes you think walking is for suckers.",
    'jetpack1': "Keep your head in the clouds with this amazing, personal jetpack!",
    'jetpack2': "Enhanced jetpack thrusters that consume 20% less energy but produce double the fun.",
    'tankBooster1': "Improved nano-storage cell technology allows your vac tanks to hold 30 units of whatever you can vac up.",
    'tankBooster2': "These enhanced nano-storage cells throw caution to the wind and allow you to cram 40 units into each vac tank.",
    'tankBooster3': "More is better, but in this case, it's best. These premium nano-storage cells can hold 50 units in each vac tank.",
    'tankBooster4': "The secret best vac tank available using experimental nano-storage technology that's absolutely probably maybe legal.",
    'extraTank1': "Adds an extra general-purpose vac tank.",
    'extraTank2': "Adds yet another extra general-purpose vac tank.",
    'waterTank1': "Adds a specialized vac tank that allows you to store fresh water.",
    'pulseWave1': "Adds a pulse wave emitter feature to your vacpack that pushes away slimes whenever you need some personal space.",
    'tankGuard1': "Salvages 20% of your vac tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'tankGuard2': "Salvages 40% of your vac tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'tankGuard3': "Salvages 60% of your vac's tank's contents upon accidental encounters with the slime sea or following other forms of health loss.",
    'droneKey1': "Utilizes Miles tech decryption algorithms to unlock access to archived logs on Research Drones.",
    'sureshot1': "A special vacpack upgrade that hones in on gold slime weakpoints (their secret bellybutton?) and doubles the amount of gold plorts they produce when hit.",
    'sureshot2': "Upgrades the Sureshot's focusing lens, reducing the glare from those shiny, bright gold slimes. This triples the amount of plorts they produce when hit.",
    'sureshot3': "The ultimate in Sureshot technology, this upgrade quadruples the amount of gold plorts produced when hitting gold slimes."
};

export const upgradeEffects = {
    'harvester1': [['misc/none', ''], ['upgrades/harvester', '+ Resource Harvester']],
    'health1': [['misc/health', '100 Health'], ['misc/health', '150 Health (+50)']],
    'health2': [['misc/health', '150 Health'], ['misc/health', '200 Health (+50)']],
    'health3': [['misc/health', '200 Health'], ['misc/health', '250 Health (+50)']],
    'power1': [['misc/energy', '100 Energy'], ['misc/energy', '150 Energy (+50)']],
    'power2': [['misc/energy', '150 Energy'], ['misc/energy', '200 Energy (+50)']],
    'power3': [['misc/energy', '200 Energy'], ['misc/energy', '250 Energy (+50)']],
    'power4': [['misc/energy', '250 Energy'], ['misc/energy', '275 Energy (+25)']],
    'dash1': [['misc/none', ''], ['upgrades/dash', '- Sprint Energy Consumption']],
    'dash2': [['misc/none', ''], ['upgrades/dash', '- Sprint Energy Consumption']],
    'jetpack1': [['misc/none', ''], ['upgrades/jetpack', 'Jetpack']],
    'jetpack2': [['misc/none', 'Jetpack'], ['upgrades/jetpack', '- Jetpack Energy Consumption']],
    'tankBooster1': [['upgrades/tankBooster', '20 Units Capacity'], ['upgrades/tankBooster', '30 Units Capacity (+10)']],
    'tankBooster2': [['upgrades/tankBooster', '30 Units Capacity'], ['upgrades/tankBooster', '40 Units Capacity (+10)']],
    'tankBooster3': [['upgrades/tankBooster', '40 Units Capacity'], ['upgrades/tankBooster', '50 Units Capacity (+10)']],
    'tankBooster4': [['upgrades/tankBooster', '50 Units Capacity'], ['upgrades/tankBooster', '60 Units Capacity (+10)']],
    'extraTank1': [['upgrades/extraTank', '4 Tanks'], ['upgrades/extraTank', '5 Tanks (+1)']],
    'extraTank2': [['upgrades/extraTank', '5 Tanks'], ['upgrades/extraTank', '6 Tanks (+1)']],
    'waterTank1': [['misc/none', ''], ['upgrades/waterTank', '+ Water Tank']],
    'pulseWave1': [['misc/none', ''], ['upgrades/pulseWave', '+ Pulse Wave']],
    'tankGuard1': [['misc/death', 'Full Loss on Death'], ['upgrades/tankGuard', '30% Salvage on Death']],
    'tankGuard2': [['upgrades/tankGuard', '30% Salvage on Death'], ['upgrades/tankGuard', '40% Salvage on Death']],
    'tankGuard3': [['upgrades/tankGuard', '40% Salvage on Death'], ['upgrades/tankGuard', '60% Salvage on Death']],
    'droneKey1': [['misc/none', ''], ['upgrades/droneKey', '+ Drone Archive Key']],
    'sureshot1': [['slimes/gold', '1 Plorts per Gold Slime Fed'], ['slimes/gold', '2 Plorts per Gold Slime Fed']],
    'sureshot2': [['slimes/gold', '2 Plorts per Gold Slime Fed'], ['slimes/gold', '3 Plorts per Gold Slime Fed']],
    'sureshot3': [['slimes/gold', '3 Plorts per Gold Slime Fed'], ['slimes/gold', '4 Plorts per Gold Slime Fed']]
};

export const warpNames = [
    "teleporthomegreen",
    "teleporthomeblue",
    "teleporthomered",
    "teleporthomeyellow",
    "teleportev",
    "teleportss",
    "teleportpb",
    "teleportblue",
    "teleportgrey",
    "teleportpink",
    "teleportviolet",
    "teleportwhite",
    "warpdepotblue",
    "warpdepotgrey",
    "warpdepotpink",
    "warpdepotviolet",
    "warpdepotwhite",
    "marketlink",
    "refinerylink",
    "linkedcannonblue",
    "linkedcannongrey",
    "linkedcannonpink"
];

export const warpGadgets = {
    'teleporthomegreen': ['Green Home Portal', 'viktor', { 'newbucks': 800, 'angler': 20, 'radiant': 10, 'wax': 10, 'wildHoney': 5 }],
    'teleporthomeblue': ['Blue Home Portal', 'viktor', { 'newbucks': 250, 'rock': 10, 'radiant': 10, 'primordy': 5 }],
    'teleporthomered': ['Red Home Portal', 'viktor', { 'newbucks': 800, 'boom': 20, 'jelly': 10, 'primordy': 10, 'lava': 5 }],
    'teleporthomeyellow': ['Yellow Home Portal', 'viktor', { 'newbucks': 250, 'cotton': 10, 'jelly': 10, 'brine': 10 }],
    'teleportev': ['Ember Valley Portal', 'pod', { 'newbucks': 1000, 'fire': 20, 'crystal': 10, 'radiant': 10, 'primordy': 10, 'diamond': 1 }],
    'teleportss': ['Starlight Strand Portal', 'pod', { 'newbucks': 1000, 'hunter': 20, 'honey': 10, 'radiant': 10, 'wax': 10, 'diamond': 1 }],
    'teleportpb': ['Powderfall Bluffs Portal', 'pod', { 'newbucks': 1000, 'saber': 20, 'puddle': 5, 'radiant': 10, 'fossil': 10, 'diamond': 1 }],
    'teleportblue': ['Blue Teleporter', 'viktor', { 'newbucks': 1200, 'rock': 30, 'brine': 20, 'radiant': 20, 'honey': 10, 'diamond': 2 }],
    'teleportgrey': ['Grey Teleporter', 'viktor', { 'newbucks': 1200, 'tabby': 30, 'wax': 20, 'radiant': 20, 'sand': 10, 'diamond': 2 }],
    'teleportpink': ['Pink Teleporter', 'viktor', { 'newbucks': 1200, 'pink': 30, 'jelly': 20, 'radiant': 20, 'lava': 10, 'diamond': 2 }],
    'teleportviolet': ['Violet Teleporter', 'viktor', { 'newbucks': 1200, 'phosphor': 30, 'primordy': 20, 'radiant': 20, 'sand': 10, 'diamond': 2 }],
    'teleportwhite': ['Snowy Teleporter', 'viktor', { 'newbucks': 1200, 'saber': 30, 'fossil': 20, 'radiant': 20, 'lava': 10, 'diamond': 2 }],
    'warpdepotblue': ['Blue Warp Depot', 'pod', { 'newbucks': 250, 'rock': 20, 'wax': 10, 'radiant': 3, 'sand': 3 }],
    'warpdepotgrey': ['Grey Warp Depot', 'pod', { 'newbucks': 250, 'tabby': 20, 'brine': 10, 'radiant': 5, 'lava': 3 }],
    'warpdepotpink': ['Pink Warp Depot', 'pod', { 'newbucks': 250, 'pink': 20, 'primordy': 10, 'radiant': 5, 'sand': 3 }],
    'warpdepotviolet': ['Violet Warp Depot', 'pod', { 'newbucks': 250, 'batty': 20, 'jelly': 10, 'radiant': 5, 'wildHoney': 3 }],
    'warpdepotwhite': ['Snowy Warp Depot', 'pod', { 'newbucks': 250, 'saber': 20, 'snowflake': 10, 'radiant': 5, 'wildHoney': 3 }],
    'marketlink': ['Market Link', 'mochi', { 'newbucks': 250, 'pink': 20, 'wax': 10, 'primordy': 10, 'sand': 5 }],
    'refinerylink': ['Refinery Link', 'mochi', { 'newbucks': 250, 'phosphor': 10, 'jelly': 10, 'brine': 5 }],
    'linkedcannonblue': ['Blue Linked Cannon', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
    'linkedcannongrey': ['Grey Linked Cannon', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
    'linkedcannonpink': ['Pink Linked Cannon', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
    'linkedcannonblueout': ['Blue Linked Cannon Output', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
    'linkedcannongreyout': ['Grey Linked Cannon Output', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
    'linkedcannonpinkout': ['Pink Linked Cannon Output', 'polestar', { 'newbucks': 1000, 'batty': 10, 'mote': 3 }],
};

export const warpDescriptions = {
    'teleporthomegreen': "A teleporter that allows for one-way travel back to the Conservatory.",
    'teleporthomeblue': "A teleporter that allows for one-way travel back to the Conservatory.",
    'teleporthomered': "A teleporter that allows for one-way travel back to the Conservatory.",
    'teleporthomeyellow': "A teleporter that allows for one-way travel back to the Conservatory.",
    'teleportev': "A teleporter that hacks the warp network on Rainbow Island, allowing one-way travel to Ember Valley.",
    'teleportss': "A teleporter that hacks the warp network on Rainbow Island, allowing one-way travel to Starlight Strand.",
    'teleportpb': "A teleporter that hacks the warp network on Rainbow Island, allowing one-way travel to Powderfall Bluffs.",
    'teleportblue': "A set of two teleporters that can be used to create your own quick travel link.",
    'teleportgrey': "A set of two teleporters that can be used to create your own quick travel link.",
    'teleportpink': "A set of two teleporters that can be used to create your own quick travel link.",
    'teleportviolet': "A set of two teleporters that can be used to create your own quick travel link.",
    'teleportwhite': "A set of two teleporters that can be used to create your own quick travel link.",
    'warpdepotblue': "A set of two gadgets that allow you to remotely transfer resources between two points.",
    'warpdepotgrey': "A set of two gadgets that allow you to remotely transfer resources between two points.",
    'warpdepotpink': "A set of two gadgets that allow you to remotely transfer resources between two points.",
    'warpdepotviolet': "A set of two gadgets that allow you to remotely transfer resources between two points.",
    'warpdepotwhite': "A set of two gadgets that allow you to remotely transfer resources between two points.",
    'marketlink': "A compact plort market that allows you to make quick sales. Consult the main plort market for price data.",
    'refinerylink': "Allows you to remotely deposit resources into the refinery.",
    'linkedcannonblue': "Combining ancient warp technology and slime science allows the two sides of this linked cannon to efficiently transport items across distances.",
    'linkedcannongrey': "Combining ancient warp technology and slime science allows the two sides of this linked cannon to efficiently transport items across distances.",
    'linkedcannonpink': "Combining ancient warp technology and slime science allows the two sides of this linked cannon to efficiently transport items across distances.",
};

export const utilitiesNames = [
    'medstation',
    'dashpad',
    'springpad',
    'turret',
    'superturret',
    'shower',
    'tamingbell',
    'watertap',
    'portablescareslime',
    'snarenovice',
    'snareadvanced',
    'baitpogo',
    'baitcarrot',
    'baitchicken',
    'slimestage',
    'snowballmachine',
    'fan',
    'bumper',
    'cannon',
    'accelerator',
    'goal',
    'markerexcl',
    'markerno',
    'markerquestion',
    'markerfruit',
    'markerveggie',
    'markermeat',
    'markerresource',
    'markermineral',
    'markerhive'
];

export const utilitiesList = {
    'medstation': ['Med Station', 'viktor', { 'newbucks': 100, 'pink': 10, 'brine': 10, 'jelly': 5 }],
    'dashpad': ['Dash Pad', 'pod', { 'newbucks': 500, 'crystal': 10, 'angler': 10, 'lava': 5, 'sand': 5 }],
    'springpad': ['Spring Pad', 'pod', { 'newbucks': 500, 'cotton': 10, 'phosphor': 10, 'sand': 5, 'honey': 5 }],
    'turret': ['Hydro Turret', 'pod', { 'newbucks': 250, 'boom': 10, 'puddle': 5, 'brine': 5 }],
    'superturret': ['Super Turret', 'ogden', { 'newbucks': 500, 'boom': 30, 'puddle': 10, 'brine': 10, 'sand': 5 }],
    'shower': ['Hydro Shower', 'pod', { 'newbucks': 500, 'flutter': 40, 'puddle': 10, 'snowflake': 10, 'wildHoney': 5 }],
    'tamingbell': ['Taming Bell', 'thora', { 'newbucks': 250, 'flutter': 10, 'cotton': 10, 'primordy': 10, 'wildHoney': 5 }],
    'watertap': ['Portable Water Tap', 'ogden', { 'newbucks': 250, 'puddle': 10, 'angler': 10, 'brine': 10, 'radiant': 5 }],
    'portablescareslime': ['Portable Scare Slime', 'ogden', { 'newbucks': 250, 'batty': 30, 'ringtail': 10, 'jelly': 10, 'sand': 5 }],
    'snarenovice': ['Novice Gordo Snare', 'pod', { 'newbucks': 250, 'hunter': 10, 'primordy': 10, 'wax': 10, 'jelly': 10 }],
    'snareadvanced': ['Advanced Gordo Snare', 'thora', { 'newbucks': 500, 'hunter': 20, 'flutter': 10, 'radiant': 10, 'wildHoney': 5, 'lava': 5 }],
    'baitpogo': ['Fruit Slime Bait', 'pod', { 'newbucks': 250, 'phosphor': 20, 'batty': 10, 'honey': 10, 'wax': 10 }],
    'baitcarrot': ['Veggie Slime Bait', 'pod', { 'newbucks': 250, 'cotton': 20, 'rock': 10, 'crystal': 10, 'radiant': 10 }],
    'baitchicken': ['Meat Slime Bait', 'pod', { 'newbucks': 250, 'tabby': 20, 'boom': 10, 'hunter': 10, 'primordy': 10 }],
    'slimestage': ['Slime Stage', 'pod', { 'newbucks': 500, 'pink': 20, 'tabby': 10, 'wax': 10, 'lava': 5 }],
    'snowballmachine': ['Snowball Machine', 'pod', { 'newbucks': 2000, 'saber': 20, 'snowflake': 10, 'diamond': 1 }],
    'fan': ['Easy Breezy Fan', 'pod', { 'newbucks': 500, 'dervish': 10, 'rock': 5, 'brine': 3 }],
    'bumper': ['Round Bumper', 'pod', { 'newbucks': 500, 'pink': 10, 'saber': 10, 'primordy': 3 }],
    'cannon': ['Stunt Cannon', 'pod', { 'newbucks': 1000, 'boom': 20, 'fire': 5, 'lava': 3 }],
    'accelerator': ['Accelerator', 'pod', { 'newbucks': 50, 'ringtail': 1, 'brine': 1 }],
    'goal': ['Slimeball Goal', 'polestar', { 'newbucks': 5000, 'honey': 25, 'flutter': 25, 'sand': 3 }],
    'markerexcl': ['Attention Flag', 'viktor', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markerno': ['Cautious Flag', 'viktor', { 'newbucks': 50, 'pink': 5, 'fossil': 5 }],
    'markerquestion': ['Curious Flag', 'viktor', { 'newbucks': 50, 'pink': 5, 'fossil': 5 }],
    'markerfruit': ['Fruit Flag', 'pod', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markerveggie': ['Veggie Flag', 'pod', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markermeat': ['Meat Flag', 'pod', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markerresource': ['Spout Resource Flag', 'polestar', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markermineral': ['Mineral Resource Flag', 'polestar', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }],
    'markerhive': ['Hive Resource Flag', 'polestar', { 'newbucks': 50, 'pink': 5, 'jelly': 5 }]
};

export const utilitiesDescription = {
    'medstation': "Rapidly drains your energy to restore health. Fixes you up fast!",
    'dashpad': "Allows you to briefly sprint with zero energy cost.",
    'springpad': "Launches anything that touches it straight into the air!",
    'turret': "A defensive cannon that will automatically target Tarr and blast them with water.",
    'superturret': "An advanced defensive cannon that doubles the firepower against tarr.",
    'shower': "This oversized sprinkler system is perfect panic button for dealing with large numbers of tarr.",
    'tamingbell': "The dulcet tone of this curious bell will calm the anger of any feral slime that hears it.",
    'watertap': "Creates a refreshing fresh water spring.",
    'portablescareslime': "Used to keep slimes away from things on your ranch, or to just scare them because you're THAT person.",
    'snarenovice': "A special snare that captures a gordo slime. Bait it with food and wait...",
    'snareadvanced': "A more advanced gordo snare with less random results. Bait it with food and wait...",
    'baitpogo': "This special slime bait can be used to harmlessly attract fruit-eating slimes.",
    'baitcarrot': "This special slime bait can be used to harmlessly attract veggie-eating slimes.",
    'baitchicken': "This special slime bait can be used to harmlessly attract meat-eating slimes.",
    'slimestage': "Allows you to let other slimes know who is, unequivocally, the number one slime.",
    'snowballmachine': "The everfrost cooling system in this device provides fresh and powdery snowballs year-round.",
    'fan': "For most ranchers this fan is simply a great way to cool down on a hot day. But you're not most ranchers.",
    'bumper': "A pinball-inspired bumper that bumps around any object you throw at it. See that? You're picturing a very silly setup with enough of these and slimes, and to that we say YES.",
    'cannon': "This danger-defying cannon launches whatever is loaded into it through the air. Never get in yourself, unless you're wearing a slime as a safety helmet.",
    'accelerator': "Any object shot through this ring will gain a boost of speed. It's rumored that too many accelerators bend time and space. Accelerate responsibly!",
    'goal': "Challenge your vac skills and delight your slimes with this moving Slimeball goal! How high can you score?",
    'markerexcl': "A useful marker for when you really need to call attention to something.",
    'markerno': "A useful marker for when you need to remember to be cautious in an area.",
    'markerquestion': "A useful marker to point you towards a nearby curiosity.",
    'markerfruit': "A useful marker to call attention to any nearby fruit.",
    'markerveggie': "A useful marker to call attention to any nearby veggies.",
    'markermeat': "A useful marker to call attention to any nearby chicken nests.",
    'markerresource': "A useful marker to call attention to any nearby spout resources.",
    'markermineral': "A useful marker to call attention to any nearby mineral resources.",
    'markerhive': "A useful marker to call attention to any nearby hive resources."
};

export const decorationsNames = [
    'emeraldgrass',
    'emeraldshrubs',
    'emeraldcypress',
    'tallemeraldcypress',
    'emeraldcypresscluster',
    'goldpetalflowers',
    'rainbowgrass',
    'pinkbonsai',
    'largepinkbonsai',
    'rockfragments',
    'rockcluster',
    'rockclump',
    'smallboulder',
    'sharpboulder',
    'rainbowmound',
    'rainbowlumps',
    'shortpinkcoralcolumns',
    'overjoyedstatue',
    'ambergrass',
    'ambershrubs',
    'ambercypress',
    'tallambercypress',
    'ambercypresscluster',
    'ochrepoppies',
    'cinderspikeblossoms',
    'ashblooms',
    'sunfiredaisies',
    'shortpalm',
    'mediumpalm',
    'stalagmite',
    'stalagmitecluster',
    'shortmagmaclump',
    'tallmagmaclump',
    'magmapool',
    'roundedmagmapool',
    'gnarledashwood',
    'shortredashwood',
    'mediumredashwood',
    'tallashwood',
    'stonyegglamp',
    'happystatue'
];

export const decorationsList = {
    'emeraldgrass': ['Emerald Grass', 'thora', { 'newbucks': 25, 'tabby': 5}, 'fields'],
    'emeraldshrubs': ['Emerald Shrubs', 'ogden', { 'newbucks': 50, 'phosphor': 10}, 'fields'],
    'emeraldcypress': ['Emerald Cypress', 'pod', { 'newbucks': 50, 'tabby': 10}, 'fields'],
    'tallemeraldcypress': ['Tall Emerald Cypress', 'ogden', { 'newbucks': 50, 'puddle': 5, 'brine': 1}, 'fields'],
    'emeraldcypresscluster': ['Emerald Cypress Cluster', 'pod', { 'newbucks': 75, 'cotton': 10}, 'fields'],
    'goldpetalflowers': ['Goldpetal Flowers', 'thora', { 'newbucks': 25, 'phosphor': 5, 'brine': 1}, 'fields'],
    'rainbowgrass': ['Rainbow Grass', 'thora', { 'newbucks': 25, 'pink': 5}, 'fields'],
    'pinkbonsai': ['Pink Bonsai', 'ogden', { 'newbucks': 150, 'hunter': 20, 'jelly': 3, 'wildHoney': 2, 'wax': 2}, 'fields'],
    'largepinkbonsai': ['Large Pink Bonsai', 'pod', { 'newbucks': 200, 'honey': 20, 'jelly': 3, 'brine': 2, 'sand': 2}, 'fields'],
    'rockfragments': ['Rock Fragments', 'bob', { 'newbucks': 50, 'pink': 5, 'jelly': 1}, 'fields'],
    'rockcluster': ['Rock Cluster', 'bob', { 'newbucks': 50, 'pink': 10, 'wax': 1}, 'fields'],
    'rockclump': ['Rock Clump', 'bob', { 'newbucks': 50, 'cotton': 10, 'brine': 1}, 'fields'],
    'smallboulder': ['Small Boulder', 'pod', { 'newbucks': 50, 'cotton': 10, 'jelly': 1}, 'fields'],
    'sharpboulder': ['Sharp Boulder', 'bob', { 'newbucks': 50, 'rock': 10, 'brine': 1}, 'fields'],
    'rainbowmound': ['Rainbow Mound', 'bob', { 'newbucks': 50, 'ringtail': 10}, 'fields'],
    'rainbowlumps': ['Rainbow Lumps', 'bob', { 'newbucks': 50, 'rock': 10}, 'fields'],
    'shortpinkcoralcolumns': ['Short Pink Coral Columns', 'mochi', { 'newbucks': 100, 'angler': 5, 'jelly': 3, 'wax': 2}, 'fields'],
    'mediumpinkcoralcolumns': ['Medium Pink Coral Columns', 'ogden', { 'newbucks': 150, 'angler': 20, 'primordy': 3, 'jelly': 2, 'sand': 2}, 'fields'],
    'overjoyedstatue': ['Overjoyed Statue', 'pod', { 'newbucks': 700, 'crystal': 15, 'puddle': 10, 'hunter': 15, 'radiant': 10, 'jelly': 10}, 'fields'],
    'ambergrass': ['Amber Grass', 'thora', { 'newbucks': 25, 'pink': 5, 'jelly': 1 }, 'valley'],
    'ambershrubs': ['Amber Shrubs', 'ogden', { 'newbucks': 50, 'rock': 10 }, 'valley'],
    'ambercypress': ['Amber Cypress', 'ogden', { 'newbucks': 50, 'phosphor': 10, 'primordy': 1 }, 'valley'],
    'tallambercypress': ['Tall Amber Cypress', 'pod', { 'newbucks': 50, 'fire': 5, 'primordy': 1 }, 'valley'],
    'ambercypresscluster': ['Amber Cypress Cluster', 'pod', { 'newbucks': 50, 'tabby': 10, 'primordy':51 }, 'valley'],
    'ochrepoppies': ['Ochre Poppies', 'ogden', { 'newbucks': 25, 'pink': 5, 'primordy': 1 }, 'valley'],
    'cinderspikeblossoms': ['Cinder Spike Blossoms', 'thora', { 'newbucks': 25, 'boom': 10, 'radiant': 1 }, 'valley'],
    'ashblooms': ['Ash Blooms', 'mochi', { 'newbucks': 25, 'ringtail': 5, 'lava': 1 }, 'valley'],
    'sunfiredaisies': ['Sunfire Daisies', 'thora', { 'newbucks': 25, 'phosphor': 10, 'primordy': 1 }, 'valley'],
    'shortpalm': ['Short Palm', 'thora', { 'newbucks': 100, 'batty': 20, 'jelly': 3, 'wax': 3 }, 'valley'],
    'mediumpalm': ['Medium Palm', 'pod', { 'newbucks': 100, 'honey': 20, 'brine': 3, 'primordy': 3, 'sand': 3 }, 'valley'],
    'stalagmite': ['Stalagmite', 'pod', { 'newbucks': 50, 'crystal': 10, 'lava': 1 }, 'valley'],
    'stalagmitecluster': ['Stalagmite Cluster', 'bob', { 'newbucks': 75, 'ringtail': 10, 'brine': 1 }, 'valley'],
    'shortmagmaclump': ['Short Magma Clump', 'mochi', { 'newbucks': 100, 'crystal': 20, 'primordy': 3, 'jelly': 2 }, 'valley'],
    'tallmagmaclump': ['Tall Magma Clump', 'pod', { 'newbucks': 150, 'boom': 10, 'primordy': 3, 'brine': 2, 'lava': 2 }, 'valley'],
    'magmapool': ['Magma Pool', 'pod', { 'newbucks': 150, 'fire': 10, 'primordy': 3, 'jelly': 2, 'lava': 2 }, 'valley'],
    'roundedmagmapool': ['Rounded Magma Pool', 'mochi', { 'newbucks': 200, 'fire': 10, 'primordy': 3, 'radiant': 2, 'lava': 2 }, 'valley'],
    'gnarledashwood': ['Gnarled Ashwood', 'mochi', { 'newbucks': 100, 'crystal': 20, 'primordy': 3, 'wax': 2, 'fire': 2 }, 'valley'],
    'shortredashwood': ['Short Red Ashwood', 'mochi', { 'newbucks': 150, 'phosphor': 20, 'primordy': 3, 'jelly': 2, 'fire': 2 }, 'valley'],
    'mediumredashwood': ['Medium Red Ashwood', 'mochi', { 'newbucks': 150, 'honey': 20, 'primordy': 3, 'wax': 2, 'fire': 2 }, 'valley'],
    'tallashwood': ['Tall Ashwood', 'mochi', { 'newbucks': 150, 'crystal': 20, 'primordy': 3, 'wax': 2, 'lava': 2 }, 'valley'],
    'stonyegglamp': ['Stony Egg Lamp', 'pod', { 'newbucks': 2500, 'yolky': 10, 'fossil': 5, 'primordy': 5, 'lava': 2 }, 'valley'],
    'happystatue': ['Happy Statue', 'pod', { 'newbucks': 700, 'flutter': 15, 'pink': 15, 'batty': 15, 'radiant': 10, 'primordy': 10 }, 'valley']
};

export const decorationsDescription = {
    'emeraldgrass': "A small patch of idyllic, lush grass that never needs watering. Truly miraculous!",
    'emeraldshrubs': "Vibrantly green and often found near cypresses, they will not grow into trees. They're shrubs.",
    'emeraldcypress': "A tree whose leaves are a rich emerald color. They're just leaves though, and won't make you rich.",
    'tallemeraldcypress': "This cypress is extra lush and healthy. It must be because it's taller and gets more sunlight.",
    'emeraldcypresscluster': "A group of cypress trees is a great start for a grove. Two times more effective than a lone tree.",
    'goldpetalflowers': "Lustrous and glittering, these flowers definitely aren't gold but are beautiful nonetheless.",
    'rainbowgrass': "This unique ground cover ripples with all the colors of the Rainbow Fields.",
    'pinkbonsai': "This contemplative arrangement of tree and rock is guaranteed to decrease stress. It's science.",
    'largepinkbonsai': "A lovely centerpiece to any garden, this arrangement evokes peace, calm, and the joy of pink slimes.",
    'rockfragments': "Rock slimes get their spikes by rolling over fragments like these tiny shards.",
    'rockcluster': "A clump of rocks resulting from repeated rock slime impacts against larger boulders.",
    'rockclump': "Sometimes these are signs of a Rock Gordo! But most of the time they're just a bunch of rocks.",
    'smallboulder': "Larger than a pebble. Smaller than a boulder.",
    'sharpboulder': "Wind and time have sharpened this rock formation to a rough point.",
    'rainbowmound': "Rumor has it that cotton slimes perfect their jumping by bounding over these grass-covered mounds.",
    'rainbowlumps': "A dollop of soil and rocks topped and sprinkled with prismatic grass.",
    'shortpinkcorralclumn': "These coral towers are usually found submerged beneath the slime sea. Curious.",
    'mediumpinkcorralclumn': "Once populated by other aquatic life, these columns are often found where angler slimes abound.",
    'overjoyedstatue': "The only thing potentially happier than a slime is an overjoyed statue of a slime.",
    'ambergrass': "Grass that flashes with the fiery colors of fall, but without the satisfying crunch of dry grass.",
    'ambershrubs': "Orange as a pumpkin, but you can't carve them. They're shrubs.",
    'ambercypress': "Minerals in the soil give this cypress a fiery orange hue reminiscent of fall.",
    'tallambercypress': "Mineral-packed soil gives this strong cypress its signature fall hue and exceptional height.",
    'ambercypresscluster': "Good thing the soil gives these amber trees their color rather than seasons. Less leaves to sweep.",
    'ochrepoppies': "A patch of poppies whose leaves are the color of the setting sun.",
    'cinderspikeblossoms': "These blossoms glow with the heat of the magma far beneath their soil.",
    'ashblooms': "Flowers growing near lava flows that take on the burning hue of the magma beneath the surface.",
    'sunfiredaisies': "It's recommended to wear eye protection when staring straight into the center of these daisies.",
    'shortpalm': "These palms provide a nice shade-covered retreat for slimes in hot environments.",
    'mediumpalm': "These tall palms are like leafy umbrellas offering protection from the sun.",
    'stalaigmite': "Looks like a giant tooth. It's a good thing the caves they're found in are just caves. Right?",
    'stalagmitecluster': "Found often in batty slime caves, this rocky cluster resembles a pair of fangs. Creepy coincidence.",
    'shortmagmaclump': "A small clump of magma that has cooled for now.",
    'tallmagmaclump': "Bubbling up from deep underground, these magma clumps give off tremendous amounts of heat.",
    'magmapool': "There's nothing like a hot, relaxing soak in the magma pool... if you're a fire slime.",
    'roundedmagmapool': "Shaped like a natural, geothermal cauldron, the only things it'll cook are careless ranchers.",
    'gnarledashwood': "A bare, twisted tree, which means fewer leaves catching fire in the lava areas the tree is found in.",
    'shortredashwood': "Found far above lava flows, these ashwood trees have fiery red leaves.",
    'mediumredashwood': "These tall ashwood trees rise far above the heat that would cause their red leaves to wilt.",
    'tallashwood': "A tall tree that has lost its leaves. Perfect for a spooky holiday.",
    'stonyegglamp': "These rounded, stone lamps are egg-cellent ways to brighten up the night.",
    'happystatue': "Ancient sculptors captured the likeness of a well-fed slime in its natural state."
};
